name       : parlatype
version    : 1.5.2
release    : 2
source     :
    - https://github.com/gkarsay/parlatype/releases/download/v1.5.2/parlatype-1.5.2.tar.gz : e5b96c7e5e0fca7776ef158d47b9ffb49cd03890c7d546216c3d3110cc04df92
license    :
    - GPL-3.0
    - CC-By-SA-3.0
    - CC-By-SA-4.0
component  : multimedia.audio
summary    : Parlatype (GNOME audio player for transcription)
description: |
    Parlatype is a minimal audio player for manual speech transcription, written for the GNOME desktop environment. It plays audio sources to transcribe them in your favourite text application.
builddeps  :
    - itstool
    - pkgconfig(libglade-2.0)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gtk-doc)
rundeps    :
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
setup      : |
    %configure --prefix=/usr --enable-gtk-doc --enable-introspection --enable-glade-catalog --with-libreoffice
build      : |
    %make
install    : |
    %make_install
