name       : parlatype
version    : '3.1'
release    : 3
source     :
    - https://github.com/gkarsay/parlatype/releases/download/v3.1/parlatype-3.1.tar.gz : c93ffc1cac64dfda71e16744941fcf48a2a376b17ee3963e27765361da2fdb1f
homepage   : https://www.parlatype.org/
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  : multimedia.audio
summary    : Parlatype (GNOME audio player for transcription)
description: |
    Parlatype is a minimal audio player for manual speech transcription, written for the GNOME desktop environment. It plays audio sources to transcribe them in your favourite text application.
builddeps  :
    - pkgconfig(libglade-2.0)
    - pkgconfig(gladeui-2.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gtk-doc)
    - itstool
rundeps    :
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
setup      : |
    %meson_configure -Dgir=true -Dglade=true -Dgtk-doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
